### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JudeDavis1** [cm-core-team/wol-api#10]
## Completed
- [x] Migrate to Java
- [x] #226
- [x] Find a new way to get the verse from the html, current solution doesn't even work 😭🤦‍♂️ -> Jonathan
- [x] Make endpoint to get all verses in a single chapter #99 

- [x] Fix tests
- [x] Create React app for the front end... -> Jonathan
- [x] Create route for getting the verse, and exporting previously made function into its own module in a controllers folder -> Jonathan
- [x] Create route generator -> Jude
- [x] #15
- [x] Test other http request packages -> Jonathan/Jude
- [x] Frontend from TS -> JS

**Comment by j-koziel** [comment]
Closing this due to inactivity
